import java.awt.*;

public class StartUpPage extends javax.swing.JFrame 
{

    public StartUpPage() {
        initComponents();
        setLayout(null);
        Toolkit temp = getToolkit();
        Dimension dim = temp.getScreenSize();
        setSize(dim.width,dim.height);
        getContentPane().setBackground(new Color(102,102,102));
        //jLabel1.setBounds(dim.width/4+80,dim.height/20,545,641);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        newMetro = new javax.swing.JMenuItem();
        findMetro = new javax.swing.JMenuItem();
        updateMetro = new javax.swing.JMenuItem();
        deleteMetro = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        tokenBook = new javax.swing.JMenuItem();
        tokenSearch = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        cardBook = new javax.swing.JMenuItem();
        cardSearch = new javax.swing.JMenuItem();
        addBalance = new javax.swing.JMenuItem();
        newCard = new javax.swing.JMenuItem();
        updateCard = new javax.swing.JMenuItem();
        deleteCard = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        newEmployee = new javax.swing.JMenuItem();
        changePasswordEmp = new javax.swing.JMenuItem();
        deleteEmployee = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        addRoute = new javax.swing.JMenuItem();
        addStation = new javax.swing.JMenuItem();
        updatefare = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metro Application");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        setResizable(false);

        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metro4.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 60)); // NOI18N
        jLabel2.setText("Welcome To Metro Management System ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1907, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 623, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu2.setText("Metros");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        newMetro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMetro.setBackground(new java.awt.Color(255, 153, 0));
        newMetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newmetro.jpeg"))); // NOI18N
        newMetro.setText("New Metro");
        newMetro.setOpaque(true);
        newMetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMetroActionPerformed(evt);
            }
        });
        jMenu2.add(newMetro);

        findMetro.setBackground(new java.awt.Color(255, 153, 0));
        findMetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search1.png"))); // NOI18N
        findMetro.setText("Find Metro");
        findMetro.setOpaque(true);
        findMetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findMetroActionPerformed(evt);
            }
        });
        jMenu2.add(findMetro);

        updateMetro.setBackground(new java.awt.Color(255, 153, 0));
        updateMetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh1.png"))); // NOI18N
        updateMetro.setText("Update Metro");
        updateMetro.setOpaque(true);
        updateMetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMetroActionPerformed(evt);
            }
        });
        jMenu2.add(updateMetro);

        deleteMetro.setBackground(new java.awt.Color(255, 153, 0));
        deleteMetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/symbol-delete1.png"))); // NOI18N
        deleteMetro.setText("Delete Metro");
        deleteMetro.setOpaque(true);
        deleteMetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMetroActionPerformed(evt);
            }
        });
        jMenu2.add(deleteMetro);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Token");

        tokenBook.setBackground(new java.awt.Color(255, 153, 0));
        tokenBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tokenbook.jpeg"))); // NOI18N
        tokenBook.setText("Token Booking");
        tokenBook.setOpaque(true);
        tokenBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokenBookActionPerformed(evt);
            }
        });
        jMenu4.add(tokenBook);

        tokenSearch.setBackground(new java.awt.Color(255, 153, 0));
        tokenSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search1.png"))); // NOI18N
        tokenSearch.setText("Search Token");
        tokenSearch.setOpaque(true);
        tokenSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokenSearchActionPerformed(evt);
            }
        });
        jMenu4.add(tokenSearch);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Smart Card");

        cardBook.setBackground(new java.awt.Color(255, 153, 0));
        cardBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardbook.png"))); // NOI18N
        cardBook.setText("Ticket Booking");
        cardBook.setOpaque(true);
        cardBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardBookActionPerformed(evt);
            }
        });
        jMenu5.add(cardBook);

        cardSearch.setBackground(new java.awt.Color(255, 153, 0));
        cardSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search1.png"))); // NOI18N
        cardSearch.setText("Search Ticket");
        cardSearch.setOpaque(true);
        cardSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardSearchActionPerformed(evt);
            }
        });
        jMenu5.add(cardSearch);

        addBalance.setBackground(new java.awt.Color(255, 153, 0));
        addBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addbalance.jpeg"))); // NOI18N
        addBalance.setText("Add Balance");
        addBalance.setOpaque(true);
        addBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBalanceActionPerformed(evt);
            }
        });
        jMenu5.add(addBalance);

        newCard.setBackground(new java.awt.Color(255, 153, 0));
        newCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newsmartcard.png"))); // NOI18N
        newCard.setText("New Smart Card");
        newCard.setOpaque(true);
        newCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCardActionPerformed(evt);
            }
        });
        jMenu5.add(newCard);

        updateCard.setBackground(new java.awt.Color(255, 153, 0));
        updateCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh1.png"))); // NOI18N
        updateCard.setText("Update Smart Card");
        updateCard.setOpaque(true);
        updateCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCardActionPerformed(evt);
            }
        });
        jMenu5.add(updateCard);

        deleteCard.setBackground(new java.awt.Color(255, 153, 0));
        deleteCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deletesmartcard.jpeg"))); // NOI18N
        deleteCard.setText("Delete Smart Card");
        deleteCard.setOpaque(true);
        deleteCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCardActionPerformed(evt);
            }
        });
        jMenu5.add(deleteCard);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Employee");

        newEmployee.setBackground(new java.awt.Color(255, 153, 0));
        newEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee.jpeg"))); // NOI18N
        newEmployee.setText("Create Employee");
        newEmployee.setOpaque(true);
        newEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeActionPerformed(evt);
            }
        });
        jMenu6.add(newEmployee);

        changePasswordEmp.setBackground(new java.awt.Color(255, 153, 0));
        changePasswordEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/changepassword.jpg"))); // NOI18N
        changePasswordEmp.setText("Change Password");
        changePasswordEmp.setOpaque(true);
        changePasswordEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordEmpActionPerformed(evt);
            }
        });
        jMenu6.add(changePasswordEmp);

        deleteEmployee.setBackground(new java.awt.Color(255, 153, 0));
        deleteEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete-user.png"))); // NOI18N
        deleteEmployee.setText("Delete Employee");
        deleteEmployee.setOpaque(true);
        deleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeActionPerformed(evt);
            }
        });
        jMenu6.add(deleteEmployee);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Misc");

        addRoute.setBackground(new java.awt.Color(255, 153, 0));
        addRoute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addroute.jpeg"))); // NOI18N
        addRoute.setText("Add Route");
        addRoute.setOpaque(true);
        addRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRouteActionPerformed(evt);
            }
        });
        jMenu7.add(addRoute);

        addStation.setBackground(new java.awt.Color(255, 153, 0));
        addStation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/station.jpeg"))); // NOI18N
        addStation.setText("Add Station");
        addStation.setOpaque(true);
        addStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStationActionPerformed(evt);
            }
        });
        jMenu7.add(addStation);

        updatefare.setBackground(new java.awt.Color(255, 153, 0));
        updatefare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh1.png"))); // NOI18N
        updatefare.setText("Update Fare");
        updatefare.setOpaque(true);
        updatefare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatefareActionPerformed(evt);
            }
        });
        jMenu7.add(updatefare);

        jMenuBar1.add(jMenu7);

        jMenu9.setText("LogOut");
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });

        logout.setText("LogOut");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu9.add(logout);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newMetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMetroActionPerformed
        // TODO add your handling code here:
        NewMetro obj = new NewMetro();
        obj.setVisible(true);
        obj.setLocation(100,100);
        //obj.dispose();
    }//GEN-LAST:event_newMetroActionPerformed

    private void findMetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findMetroActionPerformed
      // TODO add your handling code here:
        FindMetro obj = new FindMetro();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_findMetroActionPerformed

    private void updateMetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMetroActionPerformed
        // TODO add your handling code here:
        UpdateMetro obj = new UpdateMetro();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_updateMetroActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void deleteMetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMetroActionPerformed
        // TODO add your handling code here:
        DeleteMetro obj = new DeleteMetro();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_deleteMetroActionPerformed

    private void tokenSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokenSearchActionPerformed
        // TODO add your handling code here:
        TokenSearch obj = new TokenSearch();
        obj.setVisible(true);
        obj.setLocation(100,100);  
    }//GEN-LAST:event_tokenSearchActionPerformed

    private void tokenBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokenBookActionPerformed
        // TODO add your handling code here:
        Tokenbook obj = new Tokenbook();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_tokenBookActionPerformed

    private void newEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeActionPerformed
        // TODO add your handling code here:
        NewEmployee obj = new NewEmployee();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_newEmployeeActionPerformed

    private void changePasswordEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordEmpActionPerformed
        // TODO add your handling code here:
        ChangePassword obj = new ChangePassword();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_changePasswordEmpActionPerformed

    private void deleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeActionPerformed
        // TODO add your handling code here:
        DeleteEmployee obj = new DeleteEmployee();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_deleteEmployeeActionPerformed

    private void addRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRouteActionPerformed
        // TODO add your handling code here:
        Addroute obj = new Addroute();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_addRouteActionPerformed

    private void addStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStationActionPerformed
        // TODO add your handling code here:
        AddStation obj = new AddStation();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_addStationActionPerformed

    private void updatefareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatefareActionPerformed
        // TODO add your handling code here:
        Updatefare obj = new Updatefare();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_updatefareActionPerformed

    private void cardSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardSearchActionPerformed
        // TODO add your handling code here:
        CardSearch obj = new CardSearch();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_cardSearchActionPerformed

    private void cardBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardBookActionPerformed
        // TODO add your handling code here:
        Cardbook obj = new Cardbook();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_cardBookActionPerformed

    private void addBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBalanceActionPerformed
        // TODO add your handling code here:
        Addbalance obj = new Addbalance();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_addBalanceActionPerformed

    private void newCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCardActionPerformed
        // TODO add your handling code here:
        NewSmartCard obj = new NewSmartCard();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_newCardActionPerformed

    private void updateCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCardActionPerformed
        // TODO add your handling code here:
        UpdateCard obj = new UpdateCard();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_updateCardActionPerformed

    private void deleteCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCardActionPerformed
        // TODO add your handling code here:
        DeleteCard obj = new DeleteCard();
        obj.setVisible(true);
        obj.setLocation(100,100);
    }//GEN-LAST:event_deleteCardActionPerformed

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu9ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addBalance;
    private javax.swing.JMenuItem addRoute;
    private javax.swing.JMenuItem addStation;
    private javax.swing.JMenuItem cardBook;
    private javax.swing.JMenuItem cardSearch;
    private javax.swing.JMenuItem changePasswordEmp;
    private javax.swing.JMenuItem deleteCard;
    private javax.swing.JMenuItem deleteEmployee;
    private javax.swing.JMenuItem deleteMetro;
    private javax.swing.JMenuItem findMetro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem newCard;
    private javax.swing.JMenuItem newEmployee;
    private javax.swing.JMenuItem newMetro;
    private javax.swing.JMenuItem tokenBook;
    private javax.swing.JMenuItem tokenSearch;
    private javax.swing.JMenuItem updateCard;
    private javax.swing.JMenuItem updateMetro;
    private javax.swing.JMenuItem updatefare;
    // End of variables declaration//GEN-END:variables
}
